# Generated by Django 4.1.2 on 2022-10-21 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy', models.BooleanField(verbose_name='Легкий')),
                ('normal', models.BooleanField(verbose_name='Нормальный')),
                ('hard', models.BooleanField(verbose_name='Сложный')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.level'),
        ),
    ]
