# Generated by Django 4.1.2 on 2022-10-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_products_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=25, null=True)),
                ('user_sell_int', models.IntegerField(null=True)),
            ],
        ),
    ]
