# Generated by Django 4.1.2 on 2022-10-21 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
        ('accounts', '0002_level_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='play.point'),
        ),
    ]
