# Generated by Django 4.1.2 on 2022-10-21 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_one', models.BooleanField()),
                ('session_two', models.BooleanField()),
                ('session_three', models.BooleanField()),
                ('session_four', models.BooleanField()),
                ('session_five', models.BooleanField()),
                ('session_six', models.BooleanField()),
                ('session_seven', models.BooleanField()),
                ('session_eight', models.BooleanField()),
                ('session_nine', models.BooleanField()),
                ('session_ten', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='session_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.session'),
        ),
    ]
