# Generated by Django 4.1.2 on 2022-10-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_products_product_alter_session_sessions_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='user_sell_int',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
