# Generated by Django 4.1.2 on 2022-10-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_products_user_sell_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_sell_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.products'),
        ),
    ]
