# Generated by Django 4.1.2 on 2022-10-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_money'),
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
